# Site settings
title: PerformanceGym Århus
email: aarhus@performancegym.dk
phone: "+45 2241 6614"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
google_analytics_code: "UA-58650727-1"
facebook_pixel_code: "481765978651467"

# Other settings
timezone: Europe/Copenhagen
exclude:
  - "bower_components"
  - "bower.json"
  - "vendor"
  - "node_modules"

# Build settings
kramdown:
  input: GFM
  parse_block_html: true
  remove_block_html_tags: true

sass:
  style: compressed
